### ISSUE TITLE
很牛逼的产品，希望支持原生go的api。

### ISSUE THREAD

**Issue by lgh-dev** [dolphindb/api-go#1]
很牛逼的产品，打算集成到自己的物联网项目中，由于项目采用go语言开发，希望支持原生go的api。

**Comment by hzwale** [comment]
使用当前Go api有遇到什么问题吗？
若您方便，可以发邮件到support@dolphindb.com 告知一下您的手机号或微信号，我们可以更快捷的联系到您做进一步交流，也欢迎您直接和我联系，我的电话是0571-82853925 。

**Comment by hzwale** [comment]
1.30.19版本已支持。
