### ISSUE TITLE
示例运行出错，libDolphinDBAPI.so版本有问题？

### ISSUE THREAD

**Issue by szaquila** [dolphindb/api-go#2]
centos 8底下运行示例，是不是linux版本的libDolphinDBAPI.so问题，看其它2个更新日期都比较新
go run example.go
\# example/src
src/libDolphinDBAPI.so: undefined reference to \`EVP_MD_CTX_destroy\`
src/libDolphinDBAPI.so: undefined reference to \`EVP_MD_CTX_create\`
collect2: error: ld returned 1 exit status

**Comment by Way-wzc** [comment]
原版的Go-API依赖于CGO, 使用起来有诸多限制。新版本的 api-go 已经发布，欢迎使用。
