### ISSUE TITLE
官方还在维护api-go吗？

### ISSUE THREAD

**Issue by cpcjcey** [dolphindb/api-go#4]
目前在初步测试使用中，发现了一个问题，不知是否是bug还是我使用不对：后端查询返回的TABLE ，通过raw.(*model.Table).GetColumnByName(fieldName).Data.StringList()方式，获取到的字符串列表中，SYMBOL类型的字段的值都是 数字（似乎是symbol类型的内部编号），而不是字符串。不知官方是否会继续维护api-go，希望得到明确的回复？如果是的，希望尽快修复bug或释疑。非常喜欢dolphindb，希望越做越好，也兼容更多编程语言的api。

**Comment by Way-wzc** [comment]
感谢您对 dolphindb 的关注与使用，api-go 还在维护的，对于您的问题，能不能提供一下建库建表语句，SYMBOL 类型我们是有相关测试，上述的问题，可能是测试不够完善，感谢您使用 api-go。

**Comment by Way-wzc** [comment]
api-go 新版本已经发布了，您可以更新一下版本，验证一下问题是否仍然存在

**Comment by Way-wzc** [comment]
我们这边确认了一下， 您可以看一下 raw.(*model.Table).GetColumnByName(fieldName).Extend.Base.StringList() 是否能打印出数据，如果可以， 说明 Data 里存储的不是真实的数据，而是 Base 里数据的索引

**Comment by cpcjcey** [comment]
谢谢解答，采用raw.(*model.Table).GetColumnByName(fieldName).Extend.Base.StringList()的方式，顺利获取到了预期数据。

**Comment by Way-wzc** [comment]
tb := raw.(*model.Table)
for _, v := range tb.GetColumnNames() {
	vct := tb.GetColumnByName(v)
	for i := 0; i < vct.Rows(); i++ {
		dt := vct.Get(i)
		fmt.Println(dt.String())
	}
}
可以使用上面的代码来遍历 table，raw.(*model.Table).GetColumnByName(fieldName).Extend.Base.StringList() 拿到的不一定是你这一列的真实数据， Base 里存的是不重复的数据，Data 里存储的是对 Base 的索引，所以该列的真实数据，应该是以 Data 里的值为索引，去 Base 里取数据。或者用我上面的代码也可以拿到真实数据

**Comment by cpcjcey** [comment]
非常感谢您的热心支持，对于Symbol类型，关于Data 和Base里的数据区别我已经理解，此问题可以关闭了，再次感谢。
