### ISSUE TITLE
go env -w  GOARCH=386    error

### ISSUE THREAD

**Issue by ntcat** [dolphindb/api-go#5]
# github.com/dolphindb/api-go/model
..\pkg\mod\github.com\dolphindb\api-go@v1.30.21\model\datatype.go:552:12: math.MaxInt64 (untyped int constant 9223372036854775807) overflows int   
..\pkg\mod\github.com\dolphindb\api-go@v1.30.21\model\datatype.go:608:15: 4294967296 (untyped int constant) overflows int
..\pkg\mod\github.com\dolphindb\api-go@v1.30.21\model\datatype.go:620:24: 4294967296 (untyped int constant) overflows int
..\pkg\mod\github.com\dolphindb\api-go@v1.30.21\model\datatype.go:632:24: 4294967296 (untyped int constant) overflows int

**Comment by ntcat** [comment]
return ((math.MaxInt % buckets) + 2 + ((math.MaxInt + int(value)) % buckets)) % buckets

**Comment by ntcat** [comment]
return ((math.MaxInt64 % buckets) + 2 + ((math.MaxInt64 + int(value)) % buckets)) % buckets 原来是这样的，不对

**Comment by ntcat** [comment]
return (r + 4294967296) % buckets  ->  replace all 4294967296 to  math.MaxInt/2

**Comment by tourer-zc** [comment]
好的，我们将会在工作日确认一下，然后修复这个问题，感谢您的宝贵意见。

**Comment by tourer-zc** [comment]
我这边确认了一下，我们这边暂时不考虑支持 32 位系统
